name: tests

on:
  push:
    tags:
      - v*
    branches:
      - actions
      - main
  pull_request:

jobs:
  hord:
    runs-on: ubuntu-latest
    container: madflojo/ubuntu-build
    steps:
    - uses: actions/checkout@v5
    # Using this instead of actions/setup-go to get around an issue with act
    - name: Install Go
      run: |
           curl -L https://go.dev/dl/go1.24.1.linux-amd64.tar.gz | tar -C /usr/local -xzf -
    - name: Execute Tests
      run: |
        /usr/local/go/bin/go test -v -race -covermode=atomic -coverprofile=coverage.out .
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
    
  cassandra:
    runs-on: ubuntu-latest
    container: madflojo/ubuntu-build
    services:
      cassandra-primary:
        image: madflojo/cassandra:latest
        env:
          CASSANDRA_KEYSPACE: hord
        ports:
          - 7000
          - 7001
          - 7199
          - 9042
          - 9160

      cassandra:
        image: madflojo/cassandra:latest
        env:
          CASSANDRA_SEEDS: cassandra-primary
          CASSANDRA_KEYSPACE: hord
          SLEEP_TIMER: 15
        ports:
          - 7000
          - 7001
          - 7199
          - 9042
          - 9160
    steps:
    - uses: actions/checkout@v5
    # Using this instead of actions/setup-go to get around an issue with act
    - name: Install Go
      run: |
           curl -L https://go.dev/dl/go1.24.1.linux-amd64.tar.gz | tar -C /usr/local -xzf -
    - name: Execute Tests
      run: |
        sleep 120 
        cd drivers/cassandra
        /usr/local/go/bin/go test -v -race -covermode=atomic -coverprofile=coverage.out ./...
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5

  redis:
    runs-on: ubuntu-latest
    container: madflojo/ubuntu-build
    services:
      dragonfly:
        image: docker.dragonflydb.io/dragonflydb/dragonfly
        options: >-
          --health-cmd "nc -z localhost 6379"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      keydb:
        image: eqalpha/keydb

      redis:
        image: bitnami/redis:latest
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          ALLOW_EMPTY_PASSWORD: yes

      redis-sentinel:
        image: bitnami/redis-sentinel:latest
        env:
          REDIS_URL: redis://redis:6379
    steps:
    - uses: actions/checkout@v5
    # Using this instead of actions/setup-go to get around an issue with act
    - name: Install Go
      run: |
           curl -L https://go.dev/dl/go1.24.1.linux-amd64.tar.gz | tar -C /usr/local -xzf -
    - name: Execute Tests
      run: |
        cd drivers/redis
        /usr/local/go/bin/go test -v -race -covermode=atomic -coverprofile=coverage.out ./...
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5

  nats:
    runs-on: ubuntu-latest
    container: madflojo/ubuntu-build
    services:
      nats:
        image: madflojo/nats
        ports:
          - 8222
        env:
          NATS_EXTRA_FLAGS: -js
      nojsnats:
        image: madflojo/nats
        ports:
          - 8222

    steps:
    - uses: actions/checkout@v5
    # Using this instead of actions/setup-go to get around an issue with act
    - name: Install Go
      run: |
           curl -L https://go.dev/dl/go1.24.1.linux-amd64.tar.gz | tar -C /usr/local -xzf -
    - name: Execute Tests
      run: |
        cd drivers/nats
        /usr/local/go/bin/go test -v -race -covermode=atomic -coverprofile=coverage.out ./...
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5

  mock:
    runs-on: ubuntu-latest
    container: madflojo/ubuntu-build
    steps:
    - uses: actions/checkout@v5
    # Using this instead of actions/setup-go to get around an issue with act
    - name: Install Go
      run: |
           curl -L https://go.dev/dl/go1.24.1.linux-amd64.tar.gz | tar -C /usr/local -xzf -
    - name: Execute Tests
      run: |
        cd drivers/mock
        /usr/local/go/bin/go test -v -race -covermode=atomic -coverprofile=coverage.out ./...
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5

  hashmap:
    runs-on: ubuntu-latest
    container: madflojo/ubuntu-build
    steps:
    - uses: actions/checkout@v5
    # Using this instead of actions/setup-go to get around an issue with act
    - name: Install Go
      run: |
           curl -L https://go.dev/dl/go1.24.1.linux-amd64.tar.gz | tar -C /usr/local -xzf -
    - name: Execute Tests
      run: |
        cd drivers/hashmap
        /usr/local/go/bin/go test -v -race -covermode=atomic -coverprofile=coverage.out ./...
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5

  boltdb:
    runs-on: ubuntu-latest
    container: madflojo/ubuntu-build
    steps:
    - uses: actions/checkout@v5
    # Using this instead of actions/setup-go to get around an issue with act
    - name: Install Go
      run: |
           curl -L https://go.dev/dl/go1.24.1.linux-amd64.tar.gz | tar -C /usr/local -xzf -
    - name: Execute Tests
      run: |
        cd drivers/bbolt
        /usr/local/go/bin/go test -v -race -covermode=atomic -coverprofile=coverage.out ./...
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5

  cache:
    runs-on: ubuntu-latest
    container: madflojo/ubuntu-build
    services:
      cassandra-primary:
        image: madflojo/cassandra:latest
        env:
          CASSANDRA_KEYSPACE: hord
        ports:
          - 7000
          - 7001
          - 7199
          - 9042
          - 9160

      cassandra:
        image: madflojo/cassandra:latest
        env:
          CASSANDRA_SEEDS: cassandra-primary
          CASSANDRA_KEYSPACE: hord
          SLEEP_TIMER: 15
        ports:
          - 7000
          - 7001
          - 7199
          - 9042
          - 9160

      redis:
        image: bitnami/redis:latest
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          ALLOW_EMPTY_PASSWORD: yes

      redis-sentinel:
        image: bitnami/redis-sentinel:latest
        env:
          REDIS_URL: redis://redis:6379

    steps:
    - uses: actions/checkout@v5
    # Using this instead of actions/setup-go to get around an issue with act
    - name: Install Go
      run: |
           sleep 120 
           curl -L https://go.dev/dl/go1.24.1.linux-amd64.tar.gz | tar -C /usr/local -xzf -
    - name: Execute Tests for Cache
      run: |
        cd cache
        /usr/local/go/bin/go test -v -race -covermode=atomic -coverprofile=coverage.out ./...
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
    - name: Execute Tests for Lookaside
      run: |
        cd cache/lookaside
        /usr/local/go/bin/go test -v -race -covermode=atomic -coverprofile=coverage.out ./...
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
